export const projectsData = [
  {
    title: "El-Yael Website",
    type: "Web Application",
    description:
      "A comprehensive platform to study for the YAEL exam in an efficient manner.",
    technologies: {
      frontend: ["React JS", "Material-UI", "Framer Motion", "Axios"],
      backend: [
        "Spring Boot",
        "Spring Security",
        "JPA/Hibernate",
        "PostgreSQL",
        "JWT",
        "JUnit Jupiter",
        "Lombok",
        "ModelMapper",
        "Docker",
      ],
      deployment: ["Amazon RDS", "Heroku", "Netlify"],
    },
    images: [],
    URL: "https://elyael.com/",
    repository: "",
  },
  {
    title: "V-Warehouse",
    type: "Web Application",
    description:
      "Virtual Warehouse is a sophisticated web application designed for the visual communication department to manage and track equipment in their virtual warehouse. The system is engineered to serve three main user roles: warehouse managers, students, and lecturers. With a robust backend and responsive frontend, V-Warehouse makes equipment tracking and management seamless and efficient.",
    technologies: {
      frontend: [
        "React JS",
        "Material-UI",
        "Framer Motion",
        "Axios",
        "CSS",
        "SASS",
      ],
      backend: [
        "Spring Boot",
        "Spring Security",
        "PostgreSQL",
        "JPA/Hibernate",
        "PostgreSQL",
        "JWT",
        "Lombok",
      ],
    },
    images: [
      "assets/Virtual-Warehouse/Virtual-Warehouse-1.png",
      "assets/Virtual-Warehouse/Virtual-Warehouse-2.png",
      "assets/Virtual-Warehouse/Virtual-Warehouse-3.png",
      "assets/Virtual-Warehouse/Virtual-Warehouse-4.png",
      "assets/Virtual-Warehouse/Virtual-Warehouse-5.png",
      "assets/Virtual-Warehouse/Virtual-Warehouse-6.png",
      "assets/Virtual-Warehouse/Virtual-Warehouse-7.png",
      "assets/Virtual-Warehouse/Virtual-Warehouse-8.png",
      "assets/Virtual-Warehouse/Virtual-Warehouse-9.png",
      "assets/Virtual-Warehouse/Virtual-Warehouse-10.png",
      "assets/Virtual-Warehouse/Virtual-Warehouse-11.png",
    ],
    URL: "",
    repository: "https://github.com/FadiBadarni/V-Warehouse",
  },
  {
    title: "Password Manager",
    type: "Desktop Application",
    description:
      "A Java-based application designed to securely store and manage user passwords. It educates users on password protection, database management, and encryption. The application uses a strong SHA-512 encryption algorithm and stores data in a MySQL database.",
    technologies: {
      languages: ["Java"],
      GUI: ["JavaFX"],
      Database: ["MySQL"],
      Security: ["SHA-512 Encryption"],
      Tools: ["SceneBuilder"],
    },
    images: [
      "assets/Password-Manager/Password-Manager-1.png",
      "assets/Password-Manager/Password-Manager-2.png",
      "assets/Password-Manager/Password-Manager-3.png",
      "assets/Password-Manager/Password-Manager-4.png",
    ],
    URL: "",
    repository: "https://github.com/FadiBadarni/Password-Manager",
  },
  {
    title: "Compiler",
    type: "System Software",
    description:
      "This advanced compiler is built with Lex and Yacc. It is designed to parse a language that resembles the syntax of C. The compiler features implementation of symbol tables, function stack tables, and scoped management for better handling of variables and functions. It can tokenize and analyze syntax, support multiple data types, manage control structures, and evaluate expressions among many other features.",
    technologies: {
      languages: ["C", "Lex", "Yacc"],
      Concepts: [
        "Lexical Analysis",
        "Syntax Analysis",
        "Symbol Tables",
        "Function Stack Tables",
        "Scopes",
      ],
      Tools: ["flex", "yacc", "cc"],
    },
    images: [],
    URL: "",
    repository: "https://github.com/FadiBadarni/Compiler",
  },
  {
    title: "React-Portfolio",
    type: "Web Application",
    description:
      "A responsive and interactive personal portfolio website built using React. The portfolio features sections about personal details, skills, work projects, and contact information. It showcases proficiency in front-end web development with a focus on React and CSS. Additional features include a navigation bar and dots for easy access, a skills section displaying various technologies, a work section with project descriptions and images, contact information, social media icons, and email functionality, along with a downloadable resume.",
    technologies: {
      Frontend: [
        "React",
        "SCSS",
        "Framer Motion",
        "react-icons",
        "react-tooltip",
      ],
      Backend: [],
      Libraries: ["emailjs/browser", "file-saver"],
    },
    images: [],
    URL: "",
    repository: "https://github.com/FadiBadarni/React-Portfolio",
  },
  {
    title: "Medical-Diagnosis",
    type: "Desktop Application",
    description:
      "A medical diagnosis application developed for educational purposes, using Java and JavaFX. The application analyzes blood test results to provide diagnostic insights. It offers features like user registration, manual input of results, and an exportable final diagnosis.",
    technologies: {
      languages: ["Java"],
      GUI: ["JavaFX"],
      Database: ["CSV files"],
      Tools: ["SceneBuilder"],
    },
    images: [
      "assets/Medical-Diagnosis/Medical-Diagnosis-1.png",
      "assets/Medical-Diagnosis/Medical-Diagnosis-2.png",
      "assets/Medical-Diagnosis/Medical-Diagnosis-3.png",
      "assets/Medical-Diagnosis/Medical-Diagnosis-4.png",
      "assets/Medical-Diagnosis/Medical-Diagnosis-5.png",
    ],
    URL: "",
    repository: "https://github.com/FadiBadarni/Medical-Diagnosis",
  },
  {
    title: "KeyLogger",
    type: "System Software",
    description:
      "KeyLogger is an educational keystroke logging application developed in Python. Designed to demonstrate the fundamentals of keyloggers and spying malware, this application records user keyboard interactions, mouse movements, and takes screen snapshots. It offers configurable screen capture intervals and organizes recorded data in directories. It also supports sending this data to a designated email address. The application features a decoy image upon startup to mask its activities. Disclaimer: This application is for educational purposes only and should not be used for monitoring or collecting personal information without consent.",
    technologies: {
      Backend: ["Python"],
      GUI: ["Tkinter"],
    },
    images: [],
    URL: "",
    repository: "https://github.com/FadiBadarni/KeyLogger",
  },
  {
    title: "FlyWithMe",
    type: "Web Application",
    description:
      "FlyWithMe is a collaborative project developed as part of an introduction to networking course. It is a flight booking system featuring user experience enhancements, advanced search functionality, robust security measures, a seat reservation system, and diverse payment options. Built with ASP.NET, C#, and Firebase, the platform is both seamless and intuitive, aimed to provide users with a highly secure and convenient way to book flights.",
    technologies: {
      Backend: ["ASP.NET", "C#", "Firebase"],
      Frontend: ["CSS", "JavaScript"],
      Security: ["AES ", "Firewalls"],
    },
    images: [],
    URL: "",
    repository: "https://github.com/FadiBadarni/FlyWithMe",
  },
  {
    title: "Car Wash Simulation",
    type: "System Software",
    description:
      "A simulation project that models a car wash station using various concepts of concurrent programming such as processes, shared memory, and semaphores. The simulation deals with processes that represent each arriving car, shared memory for queue management, and semaphores for synchronized access.",
    technologies: {
      languages: ["C"],
      concepts: [
        "Processes",
        "Shared Memory",
        "Semaphores",
        "Exponential Distribution",
        "Signal Handling",
      ],
      tools: ["gcc"],
      libraries: ["pthread", "rt"],
    },
    URL: "",
    repository: "https://github.com/FadiBadarni/Car-Wash",
  },
];
